### ISSUE TITLE
Bug while init

### ISSUE THREAD

**Issue by kotsh23** [maniac-tech/react-native-expo-read-sms#18] opened 2022-11-20 13:46 UTC
**Describe the bug**
i'm using expo 45 
built dev apk by eas build -p android --profile development
installed on real device

App.js
```
import { StatusBar } from "expo-status-bar";
import { StyleSheet, Text, View } from "react-native";
import {
  startReadSMS,
  checkIfHasSMSPermission,
  requestReadSMSPermission,
} from "@maniac-tech/react-native-expo-read-sms";
import { useEffect } from "react";

export default function App() {
  useEffect(() => {
    if (checkIfHasSMSPermission) read();
    // requestReadSMSPermission();
    return () => {};
  }, []);

  async function read() {
    await startReadSMS(successCallbackFn);
  }
  async function successCallbackFn(status, sms, error) {
    console.log("successCallbackFn", status, sms, error);
  }

  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});

```

error i get 
```
`new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
at node_modules\expo\build\environment\react-native-logs.fx.js:18:22 in warn
at node_modules\react-native\Libraries\EventEmitter\NativeEventEmitter.js:67:20 in constructor
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:463:12 in __invokeCallback
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:125:27 in __guard$argument_0
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:368:10 in __guard   
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:124:16 in invokeCallbackAndReturnFlushedQueue
```

**Comment by maniac-tech** [comment] 2022-11-20 17:19
@kotsh23 : Are you sure you are getting this as an error, and not as a Warning?

**Comment by kotsh23** [comment] 2022-11-20 17:37
Hello @maniac-tech 
Sorry its warning :D
but nothing happen after i get new message

**Comment by maniac-tech** [comment] 2022-11-22 17:50
> Hello @maniac-tech Sorry its warning :D but nothing happen after i get new message

Did you check that the relevant SMS Permissions have been passed?

**Comment by maniac-tech** [comment] 2022-11-26 15:49
Will close this after 7 days, if there is no further conversation here.

**Comment by maniac-tech** [comment] 2022-12-03 15:15
Closing this due to no further activity

**Closed by maniac-tech** 2022-12-03 15:15 UTC
Labels: bug, good first issue

**Comment by maniac-tech** [comment] 2023-03-19 05:47
Found the explanation to this problem. The issue is happening on expo eas cloud builds as they have upgraded the npm versions. You can try these solutions mentioned [here.](https://github.com/expo/eas-cli/issues/1545#issuecomment-1331958946)
